// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _heapinfo {
 *     int *_pentry;
 *     size_t _size;
 *     int _useflag;
 * } _HEAPINFO
 * }
 */
public class _HEAPINFO$4 extends _heapinfo {

    _HEAPINFO$4() {
        // Should not be called directly
    }
}

