// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _ldiv_t {
 *     long quot;
 *     long rem;
 * }
 * }
 */
public class _ldiv_t {

    _ldiv_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_LONG.withName("quot"),
        srtp_h.C_LONG.withName("rem")
    ).withName("_ldiv_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final ValueLayout quot$LAYOUT = (ValueLayout)$LAYOUT.select(groupElement("quot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long quot
     * }
     */
    public static final ValueLayout quot$layout() { return quot$LAYOUT; }

    private static final long quot$OFFSET = $LAYOUT.byteOffset(groupElement("quot"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long quot
     * }
     */
    public static final long quot$offset() {
        return quot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long quot
     * }
     */
    public static long quot(MemorySegment struct) {
        if (quot$LAYOUT instanceof OfInt oi) return struct.get(oi, quot$OFFSET);
        if (quot$LAYOUT instanceof OfLong ol) return struct.get(ol, quot$OFFSET);
        throw new UnsupportedOperationException("Unsupported layout type: " + quot$LAYOUT);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long quot
     * }
     */
    public static void quot(MemorySegment struct, long fieldValue) {
        if (quot$LAYOUT instanceof OfInt oi) {
            struct.set(oi, quot$OFFSET, (int) fieldValue);
        } else if (quot$LAYOUT instanceof OfLong ol) {
            struct.set(ol, quot$OFFSET, fieldValue);
        }
    }

    private static final ValueLayout rem$LAYOUT = (ValueLayout)$LAYOUT.select(groupElement("rem"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long rem
     * }
     */
    public static final ValueLayout rem$layout() { return rem$LAYOUT; }

    private static final long rem$OFFSET = $LAYOUT.byteOffset(groupElement("rem"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long rem
     * }
     */
    public static final long rem$offset() {
        return rem$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long rem
     * }
     */
    public static long rem(MemorySegment struct) {
        if (rem$LAYOUT instanceof OfInt oi) return struct.get(oi, rem$OFFSET);
        if (rem$LAYOUT instanceof OfLong ol) return struct.get(ol, rem$OFFSET);
        throw new UnsupportedOperationException("Unsupported layout type: " + rem$LAYOUT);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long rem
     * }
     */
    public static void rem(MemorySegment struct, long fieldValue) {
        if (rem$LAYOUT instanceof OfInt oi) {
            struct.set(oi, rem$OFFSET, (int) fieldValue);
        } else if (rem$LAYOUT instanceof OfLong ol) {
            struct.set(ol, rem$OFFSET, fieldValue);
        }
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

