// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _lldiv_t {
 *     long long quot;
 *     long long rem;
 * } lldiv_t
 * }
 */
public class lldiv_t extends _lldiv_t$3 {

    lldiv_t() {
        // Should not be called directly
    }
}

