// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_cipher_test_case_t {
 *     size_t key_length_octets;
 *     const uint8_t *key;
 *     uint8_t *idx;
 *     size_t plaintext_length_octets;
 *     const uint8_t *plaintext;
 *     size_t ciphertext_length_octets;
 *     const uint8_t *ciphertext;
 *     size_t aad_length_octets;
 *     const uint8_t *aad;
 *     size_t tag_length_octets;
 *     const struct srtp_cipher_test_case_t *next_test_case;
 * }
 * }
 */
public class srtp_cipher_test_case_t {

    srtp_cipher_test_case_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_LONG_LONG.withName("key_length_octets"),
        srtp_h.C_POINTER.withName("key"),
        srtp_h.C_POINTER.withName("idx"),
        srtp_h.C_LONG_LONG.withName("plaintext_length_octets"),
        srtp_h.C_POINTER.withName("plaintext"),
        srtp_h.C_LONG_LONG.withName("ciphertext_length_octets"),
        srtp_h.C_POINTER.withName("ciphertext"),
        srtp_h.C_LONG_LONG.withName("aad_length_octets"),
        srtp_h.C_POINTER.withName("aad"),
        srtp_h.C_LONG_LONG.withName("tag_length_octets"),
        srtp_h.C_POINTER.withName("next_test_case")
    ).withName("srtp_cipher_test_case_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong key_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("key_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static final OfLong key_length_octets$layout() {
        return key_length_octets$LAYOUT;
    }

    private static final long key_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("key_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static final long key_length_octets$offset() {
        return key_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static long key_length_octets(MemorySegment struct) {
        return struct.get(key_length_octets$LAYOUT, key_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static void key_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(key_length_octets$LAYOUT, key_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout key$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static final AddressLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.get(key$LAYOUT, key$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(key$LAYOUT, key$OFFSET, fieldValue);
    }

    private static final AddressLayout idx$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("idx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t *idx
     * }
     */
    public static final AddressLayout idx$layout() {
        return idx$LAYOUT;
    }

    private static final long idx$OFFSET = $LAYOUT.byteOffset(groupElement("idx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t *idx
     * }
     */
    public static final long idx$offset() {
        return idx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t *idx
     * }
     */
    public static MemorySegment idx(MemorySegment struct) {
        return struct.get(idx$LAYOUT, idx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t *idx
     * }
     */
    public static void idx(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(idx$LAYOUT, idx$OFFSET, fieldValue);
    }

    private static final OfLong plaintext_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("plaintext_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t plaintext_length_octets
     * }
     */
    public static final OfLong plaintext_length_octets$layout() {
        return plaintext_length_octets$LAYOUT;
    }

    private static final long plaintext_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("plaintext_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t plaintext_length_octets
     * }
     */
    public static final long plaintext_length_octets$offset() {
        return plaintext_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t plaintext_length_octets
     * }
     */
    public static long plaintext_length_octets(MemorySegment struct) {
        return struct.get(plaintext_length_octets$LAYOUT, plaintext_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t plaintext_length_octets
     * }
     */
    public static void plaintext_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(plaintext_length_octets$LAYOUT, plaintext_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout plaintext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("plaintext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *plaintext
     * }
     */
    public static final AddressLayout plaintext$layout() {
        return plaintext$LAYOUT;
    }

    private static final long plaintext$OFFSET = $LAYOUT.byteOffset(groupElement("plaintext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *plaintext
     * }
     */
    public static final long plaintext$offset() {
        return plaintext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *plaintext
     * }
     */
    public static MemorySegment plaintext(MemorySegment struct) {
        return struct.get(plaintext$LAYOUT, plaintext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *plaintext
     * }
     */
    public static void plaintext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(plaintext$LAYOUT, plaintext$OFFSET, fieldValue);
    }

    private static final OfLong ciphertext_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ciphertext_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t ciphertext_length_octets
     * }
     */
    public static final OfLong ciphertext_length_octets$layout() {
        return ciphertext_length_octets$LAYOUT;
    }

    private static final long ciphertext_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("ciphertext_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t ciphertext_length_octets
     * }
     */
    public static final long ciphertext_length_octets$offset() {
        return ciphertext_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t ciphertext_length_octets
     * }
     */
    public static long ciphertext_length_octets(MemorySegment struct) {
        return struct.get(ciphertext_length_octets$LAYOUT, ciphertext_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t ciphertext_length_octets
     * }
     */
    public static void ciphertext_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(ciphertext_length_octets$LAYOUT, ciphertext_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout ciphertext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ciphertext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *ciphertext
     * }
     */
    public static final AddressLayout ciphertext$layout() {
        return ciphertext$LAYOUT;
    }

    private static final long ciphertext$OFFSET = $LAYOUT.byteOffset(groupElement("ciphertext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *ciphertext
     * }
     */
    public static final long ciphertext$offset() {
        return ciphertext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *ciphertext
     * }
     */
    public static MemorySegment ciphertext(MemorySegment struct) {
        return struct.get(ciphertext$LAYOUT, ciphertext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *ciphertext
     * }
     */
    public static void ciphertext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ciphertext$LAYOUT, ciphertext$OFFSET, fieldValue);
    }

    private static final OfLong aad_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("aad_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t aad_length_octets
     * }
     */
    public static final OfLong aad_length_octets$layout() {
        return aad_length_octets$LAYOUT;
    }

    private static final long aad_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("aad_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t aad_length_octets
     * }
     */
    public static final long aad_length_octets$offset() {
        return aad_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t aad_length_octets
     * }
     */
    public static long aad_length_octets(MemorySegment struct) {
        return struct.get(aad_length_octets$LAYOUT, aad_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t aad_length_octets
     * }
     */
    public static void aad_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(aad_length_octets$LAYOUT, aad_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout aad$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("aad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *aad
     * }
     */
    public static final AddressLayout aad$layout() {
        return aad$LAYOUT;
    }

    private static final long aad$OFFSET = $LAYOUT.byteOffset(groupElement("aad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *aad
     * }
     */
    public static final long aad$offset() {
        return aad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *aad
     * }
     */
    public static MemorySegment aad(MemorySegment struct) {
        return struct.get(aad$LAYOUT, aad$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *aad
     * }
     */
    public static void aad(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(aad$LAYOUT, aad$OFFSET, fieldValue);
    }

    private static final OfLong tag_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tag_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static final OfLong tag_length_octets$layout() {
        return tag_length_octets$LAYOUT;
    }

    private static final long tag_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("tag_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static final long tag_length_octets$offset() {
        return tag_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static long tag_length_octets(MemorySegment struct) {
        return struct.get(tag_length_octets$LAYOUT, tag_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static void tag_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(tag_length_octets$LAYOUT, tag_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout next_test_case$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next_test_case"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct srtp_cipher_test_case_t *next_test_case
     * }
     */
    public static final AddressLayout next_test_case$layout() {
        return next_test_case$LAYOUT;
    }

    private static final long next_test_case$OFFSET = $LAYOUT.byteOffset(groupElement("next_test_case"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct srtp_cipher_test_case_t *next_test_case
     * }
     */
    public static final long next_test_case$offset() {
        return next_test_case$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct srtp_cipher_test_case_t *next_test_case
     * }
     */
    public static MemorySegment next_test_case(MemorySegment struct) {
        return struct.get(next_test_case$LAYOUT, next_test_case$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct srtp_cipher_test_case_t *next_test_case
     * }
     */
    public static void next_test_case(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next_test_case$LAYOUT, next_test_case$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

