// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_kernel_auth_type {
 *     srtp_auth_type_id_t id;
 *     const srtp_auth_type_t *auth_type;
 *     struct srtp_kernel_auth_type *next;
 * }
 * }
 */
public class srtp_kernel_auth_type {

    srtp_kernel_auth_type() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_INT.withName("id"),
        MemoryLayout.paddingLayout(4),
        srtp_h.C_POINTER.withName("auth_type"),
        srtp_h.C_POINTER.withName("next")
    ).withName("srtp_kernel_auth_type");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final AddressLayout auth_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("auth_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const srtp_auth_type_t *auth_type
     * }
     */
    public static final AddressLayout auth_type$layout() {
        return auth_type$LAYOUT;
    }

    private static final long auth_type$OFFSET = $LAYOUT.byteOffset(groupElement("auth_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const srtp_auth_type_t *auth_type
     * }
     */
    public static final long auth_type$offset() {
        return auth_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const srtp_auth_type_t *auth_type
     * }
     */
    public static MemorySegment auth_type(MemorySegment struct) {
        return struct.get(auth_type$LAYOUT, auth_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const srtp_auth_type_t *auth_type
     * }
     */
    public static void auth_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(auth_type$LAYOUT, auth_type$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct srtp_kernel_auth_type *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct srtp_kernel_auth_type *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct srtp_kernel_auth_type *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct srtp_kernel_auth_type *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

