// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_auth_test_case_t {
 *     size_t key_length_octets;
 *     const uint8_t *key;
 *     size_t data_length_octets;
 *     const uint8_t *data;
 *     size_t tag_length_octets;
 *     const uint8_t *tag;
 *     const struct srtp_auth_test_case_t *next_test_case;
 * }
 * }
 */
public class srtp_auth_test_case_t {

    srtp_auth_test_case_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_LONG_LONG.withName("key_length_octets"),
        srtp_h.C_POINTER.withName("key"),
        srtp_h.C_LONG_LONG.withName("data_length_octets"),
        srtp_h.C_POINTER.withName("data"),
        srtp_h.C_LONG_LONG.withName("tag_length_octets"),
        srtp_h.C_POINTER.withName("tag"),
        srtp_h.C_POINTER.withName("next_test_case")
    ).withName("srtp_auth_test_case_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong key_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("key_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static final OfLong key_length_octets$layout() {
        return key_length_octets$LAYOUT;
    }

    private static final long key_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("key_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static final long key_length_octets$offset() {
        return key_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static long key_length_octets(MemorySegment struct) {
        return struct.get(key_length_octets$LAYOUT, key_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t key_length_octets
     * }
     */
    public static void key_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(key_length_octets$LAYOUT, key_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout key$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static final AddressLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.get(key$LAYOUT, key$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *key
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(key$LAYOUT, key$OFFSET, fieldValue);
    }

    private static final OfLong data_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("data_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t data_length_octets
     * }
     */
    public static final OfLong data_length_octets$layout() {
        return data_length_octets$LAYOUT;
    }

    private static final long data_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("data_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t data_length_octets
     * }
     */
    public static final long data_length_octets$offset() {
        return data_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t data_length_octets
     * }
     */
    public static long data_length_octets(MemorySegment struct) {
        return struct.get(data_length_octets$LAYOUT, data_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t data_length_octets
     * }
     */
    public static void data_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(data_length_octets$LAYOUT, data_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    private static final OfLong tag_length_octets$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tag_length_octets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static final OfLong tag_length_octets$layout() {
        return tag_length_octets$LAYOUT;
    }

    private static final long tag_length_octets$OFFSET = $LAYOUT.byteOffset(groupElement("tag_length_octets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static final long tag_length_octets$offset() {
        return tag_length_octets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static long tag_length_octets(MemorySegment struct) {
        return struct.get(tag_length_octets$LAYOUT, tag_length_octets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t tag_length_octets
     * }
     */
    public static void tag_length_octets(MemorySegment struct, long fieldValue) {
        struct.set(tag_length_octets$LAYOUT, tag_length_octets$OFFSET, fieldValue);
    }

    private static final AddressLayout tag$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *tag
     * }
     */
    public static final AddressLayout tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *tag
     * }
     */
    public static MemorySegment tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *tag
     * }
     */
    public static void tag(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    private static final AddressLayout next_test_case$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next_test_case"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct srtp_auth_test_case_t *next_test_case
     * }
     */
    public static final AddressLayout next_test_case$layout() {
        return next_test_case$LAYOUT;
    }

    private static final long next_test_case$OFFSET = $LAYOUT.byteOffset(groupElement("next_test_case"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct srtp_auth_test_case_t *next_test_case
     * }
     */
    public static final long next_test_case$offset() {
        return next_test_case$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct srtp_auth_test_case_t *next_test_case
     * }
     */
    public static MemorySegment next_test_case(MemorySegment struct) {
        return struct.get(next_test_case$LAYOUT, next_test_case$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct srtp_auth_test_case_t *next_test_case
     * }
     */
    public static void next_test_case(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next_test_case$LAYOUT, next_test_case$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

