// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t window_start;
 *     v128_t bitmask;
 * }
 * }
 */
public class srtp_rdb_t {

    srtp_rdb_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_INT.withName("window_start"),
        MemoryLayout.paddingLayout(4),
        v128_t.layout().withName("bitmask")
    ).withName("$anon$61:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt window_start$LAYOUT = (OfInt)$LAYOUT.select(groupElement("window_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t window_start
     * }
     */
    public static final OfInt window_start$layout() {
        return window_start$LAYOUT;
    }

    private static final long window_start$OFFSET = $LAYOUT.byteOffset(groupElement("window_start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t window_start
     * }
     */
    public static final long window_start$offset() {
        return window_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t window_start
     * }
     */
    public static int window_start(MemorySegment struct) {
        return struct.get(window_start$LAYOUT, window_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t window_start
     * }
     */
    public static void window_start(MemorySegment struct, int fieldValue) {
        struct.set(window_start$LAYOUT, window_start$OFFSET, fieldValue);
    }

    private static final GroupLayout bitmask$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("bitmask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * v128_t bitmask
     * }
     */
    public static final GroupLayout bitmask$layout() {
        return bitmask$LAYOUT;
    }

    private static final long bitmask$OFFSET = $LAYOUT.byteOffset(groupElement("bitmask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * v128_t bitmask
     * }
     */
    public static final long bitmask$offset() {
        return bitmask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * v128_t bitmask
     * }
     */
    public static MemorySegment bitmask(MemorySegment struct) {
        return struct.asSlice(bitmask$OFFSET, bitmask$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * v128_t bitmask
     * }
     */
    public static void bitmask(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bitmask$OFFSET, bitmask$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

