// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_auth_type_t {
 *     srtp_auth_alloc_func alloc;
 *     srtp_auth_dealloc_func dealloc;
 *     srtp_auth_init_func init;
 *     srtp_auth_compute_func compute;
 *     srtp_auth_update_func update;
 *     srtp_auth_start_func start;
 *     const char *description;
 *     const srtp_auth_test_case_t *test_data;
 *     srtp_auth_type_id_t id;
 * }
 * }
 */
public class srtp_auth_type_t {

    srtp_auth_type_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_POINTER.withName("alloc"),
        srtp_h.C_POINTER.withName("dealloc"),
        srtp_h.C_POINTER.withName("init"),
        srtp_h.C_POINTER.withName("compute"),
        srtp_h.C_POINTER.withName("update"),
        srtp_h.C_POINTER.withName("start"),
        srtp_h.C_POINTER.withName("description"),
        srtp_h.C_POINTER.withName("test_data"),
        srtp_h.C_INT.withName("id"),
        MemoryLayout.paddingLayout(4)
    ).withName("srtp_auth_type_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout alloc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("alloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_alloc_func alloc
     * }
     */
    public static final AddressLayout alloc$layout() {
        return alloc$LAYOUT;
    }

    private static final long alloc$OFFSET = $LAYOUT.byteOffset(groupElement("alloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_alloc_func alloc
     * }
     */
    public static final long alloc$offset() {
        return alloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_alloc_func alloc
     * }
     */
    public static MemorySegment alloc(MemorySegment struct) {
        return struct.get(alloc$LAYOUT, alloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_alloc_func alloc
     * }
     */
    public static void alloc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(alloc$LAYOUT, alloc$OFFSET, fieldValue);
    }

    private static final AddressLayout dealloc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dealloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_dealloc_func dealloc
     * }
     */
    public static final AddressLayout dealloc$layout() {
        return dealloc$LAYOUT;
    }

    private static final long dealloc$OFFSET = $LAYOUT.byteOffset(groupElement("dealloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_dealloc_func dealloc
     * }
     */
    public static final long dealloc$offset() {
        return dealloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_dealloc_func dealloc
     * }
     */
    public static MemorySegment dealloc(MemorySegment struct) {
        return struct.get(dealloc$LAYOUT, dealloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_dealloc_func dealloc
     * }
     */
    public static void dealloc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dealloc$LAYOUT, dealloc$OFFSET, fieldValue);
    }

    private static final AddressLayout init$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_init_func init
     * }
     */
    public static final AddressLayout init$layout() {
        return init$LAYOUT;
    }

    private static final long init$OFFSET = $LAYOUT.byteOffset(groupElement("init"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_init_func init
     * }
     */
    public static final long init$offset() {
        return init$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_init_func init
     * }
     */
    public static MemorySegment init(MemorySegment struct) {
        return struct.get(init$LAYOUT, init$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_init_func init
     * }
     */
    public static void init(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init$LAYOUT, init$OFFSET, fieldValue);
    }

    private static final AddressLayout compute$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("compute"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_compute_func compute
     * }
     */
    public static final AddressLayout compute$layout() {
        return compute$LAYOUT;
    }

    private static final long compute$OFFSET = $LAYOUT.byteOffset(groupElement("compute"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_compute_func compute
     * }
     */
    public static final long compute$offset() {
        return compute$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_compute_func compute
     * }
     */
    public static MemorySegment compute(MemorySegment struct) {
        return struct.get(compute$LAYOUT, compute$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_compute_func compute
     * }
     */
    public static void compute(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(compute$LAYOUT, compute$OFFSET, fieldValue);
    }

    private static final AddressLayout update$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("update"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_update_func update
     * }
     */
    public static final AddressLayout update$layout() {
        return update$LAYOUT;
    }

    private static final long update$OFFSET = $LAYOUT.byteOffset(groupElement("update"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_update_func update
     * }
     */
    public static final long update$offset() {
        return update$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_update_func update
     * }
     */
    public static MemorySegment update(MemorySegment struct) {
        return struct.get(update$LAYOUT, update$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_update_func update
     * }
     */
    public static void update(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(update$LAYOUT, update$OFFSET, fieldValue);
    }

    private static final AddressLayout start$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_start_func start
     * }
     */
    public static final AddressLayout start$layout() {
        return start$LAYOUT;
    }

    private static final long start$OFFSET = $LAYOUT.byteOffset(groupElement("start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_start_func start
     * }
     */
    public static final long start$offset() {
        return start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_start_func start
     * }
     */
    public static MemorySegment start(MemorySegment struct) {
        return struct.get(start$LAYOUT, start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_start_func start
     * }
     */
    public static void start(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(start$LAYOUT, start$OFFSET, fieldValue);
    }

    private static final AddressLayout description$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final AddressLayout description$layout() {
        return description$LAYOUT;
    }

    private static final long description$OFFSET = $LAYOUT.byteOffset(groupElement("description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final long description$offset() {
        return description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static MemorySegment description(MemorySegment struct) {
        return struct.get(description$LAYOUT, description$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static void description(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(description$LAYOUT, description$OFFSET, fieldValue);
    }

    private static final AddressLayout test_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("test_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const srtp_auth_test_case_t *test_data
     * }
     */
    public static final AddressLayout test_data$layout() {
        return test_data$LAYOUT;
    }

    private static final long test_data$OFFSET = $LAYOUT.byteOffset(groupElement("test_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const srtp_auth_test_case_t *test_data
     * }
     */
    public static final long test_data$offset() {
        return test_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const srtp_auth_test_case_t *test_data
     * }
     */
    public static MemorySegment test_data(MemorySegment struct) {
        return struct.get(test_data$LAYOUT, test_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const srtp_auth_test_case_t *test_data
     * }
     */
    public static void test_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(test_data$LAYOUT, test_data$OFFSET, fieldValue);
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

