// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_crypto_policy_t {
 *     srtp_cipher_type_id_t cipher_type;
 *     size_t cipher_key_len;
 *     srtp_auth_type_id_t auth_type;
 *     size_t auth_key_len;
 *     size_t auth_tag_len;
 *     srtp_sec_serv_t sec_serv;
 * }
 * }
 */
public class srtp_crypto_policy_t {

    srtp_crypto_policy_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_INT.withName("cipher_type"),
        MemoryLayout.paddingLayout(4),
        srtp_h.C_LONG_LONG.withName("cipher_key_len"),
        srtp_h.C_INT.withName("auth_type"),
        MemoryLayout.paddingLayout(4),
        srtp_h.C_LONG_LONG.withName("auth_key_len"),
        srtp_h.C_LONG_LONG.withName("auth_tag_len"),
        srtp_h.C_INT.withName("sec_serv"),
        MemoryLayout.paddingLayout(4)
    ).withName("srtp_crypto_policy_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt cipher_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("cipher_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t cipher_type
     * }
     */
    public static final OfInt cipher_type$layout() {
        return cipher_type$LAYOUT;
    }

    private static final long cipher_type$OFFSET = $LAYOUT.byteOffset(groupElement("cipher_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t cipher_type
     * }
     */
    public static final long cipher_type$offset() {
        return cipher_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t cipher_type
     * }
     */
    public static int cipher_type(MemorySegment struct) {
        return struct.get(cipher_type$LAYOUT, cipher_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t cipher_type
     * }
     */
    public static void cipher_type(MemorySegment struct, int fieldValue) {
        struct.set(cipher_type$LAYOUT, cipher_type$OFFSET, fieldValue);
    }

    private static final OfLong cipher_key_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("cipher_key_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t cipher_key_len
     * }
     */
    public static final OfLong cipher_key_len$layout() {
        return cipher_key_len$LAYOUT;
    }

    private static final long cipher_key_len$OFFSET = $LAYOUT.byteOffset(groupElement("cipher_key_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t cipher_key_len
     * }
     */
    public static final long cipher_key_len$offset() {
        return cipher_key_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t cipher_key_len
     * }
     */
    public static long cipher_key_len(MemorySegment struct) {
        return struct.get(cipher_key_len$LAYOUT, cipher_key_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t cipher_key_len
     * }
     */
    public static void cipher_key_len(MemorySegment struct, long fieldValue) {
        struct.set(cipher_key_len$LAYOUT, cipher_key_len$OFFSET, fieldValue);
    }

    private static final OfInt auth_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("auth_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t auth_type
     * }
     */
    public static final OfInt auth_type$layout() {
        return auth_type$LAYOUT;
    }

    private static final long auth_type$OFFSET = $LAYOUT.byteOffset(groupElement("auth_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t auth_type
     * }
     */
    public static final long auth_type$offset() {
        return auth_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t auth_type
     * }
     */
    public static int auth_type(MemorySegment struct) {
        return struct.get(auth_type$LAYOUT, auth_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_auth_type_id_t auth_type
     * }
     */
    public static void auth_type(MemorySegment struct, int fieldValue) {
        struct.set(auth_type$LAYOUT, auth_type$OFFSET, fieldValue);
    }

    private static final OfLong auth_key_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("auth_key_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t auth_key_len
     * }
     */
    public static final OfLong auth_key_len$layout() {
        return auth_key_len$LAYOUT;
    }

    private static final long auth_key_len$OFFSET = $LAYOUT.byteOffset(groupElement("auth_key_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t auth_key_len
     * }
     */
    public static final long auth_key_len$offset() {
        return auth_key_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t auth_key_len
     * }
     */
    public static long auth_key_len(MemorySegment struct) {
        return struct.get(auth_key_len$LAYOUT, auth_key_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t auth_key_len
     * }
     */
    public static void auth_key_len(MemorySegment struct, long fieldValue) {
        struct.set(auth_key_len$LAYOUT, auth_key_len$OFFSET, fieldValue);
    }

    private static final OfLong auth_tag_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("auth_tag_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t auth_tag_len
     * }
     */
    public static final OfLong auth_tag_len$layout() {
        return auth_tag_len$LAYOUT;
    }

    private static final long auth_tag_len$OFFSET = $LAYOUT.byteOffset(groupElement("auth_tag_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t auth_tag_len
     * }
     */
    public static final long auth_tag_len$offset() {
        return auth_tag_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t auth_tag_len
     * }
     */
    public static long auth_tag_len(MemorySegment struct) {
        return struct.get(auth_tag_len$LAYOUT, auth_tag_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t auth_tag_len
     * }
     */
    public static void auth_tag_len(MemorySegment struct, long fieldValue) {
        struct.set(auth_tag_len$LAYOUT, auth_tag_len$OFFSET, fieldValue);
    }

    private static final OfInt sec_serv$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sec_serv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_sec_serv_t sec_serv
     * }
     */
    public static final OfInt sec_serv$layout() {
        return sec_serv$LAYOUT;
    }

    private static final long sec_serv$OFFSET = $LAYOUT.byteOffset(groupElement("sec_serv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_sec_serv_t sec_serv
     * }
     */
    public static final long sec_serv$offset() {
        return sec_serv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_sec_serv_t sec_serv
     * }
     */
    public static int sec_serv(MemorySegment struct) {
        return struct.get(sec_serv$LAYOUT, sec_serv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_sec_serv_t sec_serv
     * }
     */
    public static void sec_serv(MemorySegment struct, int fieldValue) {
        struct.set(sec_serv$LAYOUT, sec_serv$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

