// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef srtp_err_status_t (*srtp_cipher_encrypt_func_t)(void *, const uint8_t *, size_t, uint8_t *, size_t *)
 * }
 */
public final class srtp_cipher_encrypt_func_t {

    private srtp_cipher_encrypt_func_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment state, MemorySegment src, long src_len, MemorySegment dst, MemorySegment dst_len);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        srtp_h.C_INT,
        srtp_h.C_POINTER,
        srtp_h.C_POINTER,
        srtp_h.C_LONG_LONG,
        srtp_h.C_POINTER,
        srtp_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = srtp_h.upcallHandle(srtp_cipher_encrypt_func_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(srtp_cipher_encrypt_func_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment state, MemorySegment src, long src_len, MemorySegment dst, MemorySegment dst_len) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, state, src, src_len, dst, dst_len);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

