// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_cipher_t {
 *     const srtp_cipher_type_t *type;
 *     void *state;
 *     size_t key_len;
 *     srtp_cipher_type_id_t algorithm;
 * }
 * }
 */
public class srtp_cipher_t {

    srtp_cipher_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_POINTER.withName("type"),
        srtp_h.C_POINTER.withName("state"),
        srtp_h.C_LONG_LONG.withName("key_len"),
        srtp_h.C_INT.withName("algorithm"),
        MemoryLayout.paddingLayout(4)
    ).withName("srtp_cipher_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const srtp_cipher_type_t *type
     * }
     */
    public static final AddressLayout type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const srtp_cipher_type_t *type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const srtp_cipher_type_t *type
     * }
     */
    public static MemorySegment type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const srtp_cipher_type_t *type
     * }
     */
    public static void type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final AddressLayout state$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static final AddressLayout state$layout() {
        return state$LAYOUT;
    }

    private static final long state$OFFSET = $LAYOUT.byteOffset(groupElement("state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static final long state$offset() {
        return state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static MemorySegment state(MemorySegment struct) {
        return struct.get(state$LAYOUT, state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static void state(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(state$LAYOUT, state$OFFSET, fieldValue);
    }

    private static final OfLong key_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("key_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t key_len
     * }
     */
    public static final OfLong key_len$layout() {
        return key_len$LAYOUT;
    }

    private static final long key_len$OFFSET = $LAYOUT.byteOffset(groupElement("key_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t key_len
     * }
     */
    public static final long key_len$offset() {
        return key_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t key_len
     * }
     */
    public static long key_len(MemorySegment struct) {
        return struct.get(key_len$LAYOUT, key_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t key_len
     * }
     */
    public static void key_len(MemorySegment struct, long fieldValue) {
        struct.set(key_len$LAYOUT, key_len$OFFSET, fieldValue);
    }

    private static final OfInt algorithm$LAYOUT = (OfInt)$LAYOUT.select(groupElement("algorithm"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t algorithm
     * }
     */
    public static final OfInt algorithm$layout() {
        return algorithm$LAYOUT;
    }

    private static final long algorithm$OFFSET = $LAYOUT.byteOffset(groupElement("algorithm"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t algorithm
     * }
     */
    public static final long algorithm$offset() {
        return algorithm$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t algorithm
     * }
     */
    public static int algorithm(MemorySegment struct) {
        return struct.get(algorithm$LAYOUT, algorithm$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t algorithm
     * }
     */
    public static void algorithm(MemorySegment struct, int fieldValue) {
        struct.set(algorithm$LAYOUT, algorithm$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

