// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     srtp_crypto_kernel_state_t state;
 *     srtp_kernel_cipher_type_t *cipher_type_list;
 *     srtp_kernel_auth_type_t *auth_type_list;
 *     srtp_kernel_debug_module_t *debug_module_list;
 * }
 * }
 */
public class srtp_crypto_kernel_t {

    srtp_crypto_kernel_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_INT.withName("state"),
        MemoryLayout.paddingLayout(4),
        srtp_h.C_POINTER.withName("cipher_type_list"),
        srtp_h.C_POINTER.withName("auth_type_list"),
        srtp_h.C_POINTER.withName("debug_module_list")
    ).withName("$anon$101:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt state$LAYOUT = (OfInt)$LAYOUT.select(groupElement("state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_crypto_kernel_state_t state
     * }
     */
    public static final OfInt state$layout() {
        return state$LAYOUT;
    }

    private static final long state$OFFSET = $LAYOUT.byteOffset(groupElement("state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_crypto_kernel_state_t state
     * }
     */
    public static final long state$offset() {
        return state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_crypto_kernel_state_t state
     * }
     */
    public static int state(MemorySegment struct) {
        return struct.get(state$LAYOUT, state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_crypto_kernel_state_t state
     * }
     */
    public static void state(MemorySegment struct, int fieldValue) {
        struct.set(state$LAYOUT, state$OFFSET, fieldValue);
    }

    private static final AddressLayout cipher_type_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cipher_type_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_kernel_cipher_type_t *cipher_type_list
     * }
     */
    public static final AddressLayout cipher_type_list$layout() {
        return cipher_type_list$LAYOUT;
    }

    private static final long cipher_type_list$OFFSET = $LAYOUT.byteOffset(groupElement("cipher_type_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_kernel_cipher_type_t *cipher_type_list
     * }
     */
    public static final long cipher_type_list$offset() {
        return cipher_type_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_kernel_cipher_type_t *cipher_type_list
     * }
     */
    public static MemorySegment cipher_type_list(MemorySegment struct) {
        return struct.get(cipher_type_list$LAYOUT, cipher_type_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_kernel_cipher_type_t *cipher_type_list
     * }
     */
    public static void cipher_type_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cipher_type_list$LAYOUT, cipher_type_list$OFFSET, fieldValue);
    }

    private static final AddressLayout auth_type_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("auth_type_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_kernel_auth_type_t *auth_type_list
     * }
     */
    public static final AddressLayout auth_type_list$layout() {
        return auth_type_list$LAYOUT;
    }

    private static final long auth_type_list$OFFSET = $LAYOUT.byteOffset(groupElement("auth_type_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_kernel_auth_type_t *auth_type_list
     * }
     */
    public static final long auth_type_list$offset() {
        return auth_type_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_kernel_auth_type_t *auth_type_list
     * }
     */
    public static MemorySegment auth_type_list(MemorySegment struct) {
        return struct.get(auth_type_list$LAYOUT, auth_type_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_kernel_auth_type_t *auth_type_list
     * }
     */
    public static void auth_type_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(auth_type_list$LAYOUT, auth_type_list$OFFSET, fieldValue);
    }

    private static final AddressLayout debug_module_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("debug_module_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_kernel_debug_module_t *debug_module_list
     * }
     */
    public static final AddressLayout debug_module_list$layout() {
        return debug_module_list$LAYOUT;
    }

    private static final long debug_module_list$OFFSET = $LAYOUT.byteOffset(groupElement("debug_module_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_kernel_debug_module_t *debug_module_list
     * }
     */
    public static final long debug_module_list$offset() {
        return debug_module_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_kernel_debug_module_t *debug_module_list
     * }
     */
    public static MemorySegment debug_module_list(MemorySegment struct) {
        return struct.get(debug_module_list$LAYOUT, debug_module_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_kernel_debug_module_t *debug_module_list
     * }
     */
    public static void debug_module_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(debug_module_list$LAYOUT, debug_module_list$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

