// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_event_data_t {
 *     srtp_t session;
 *     uint32_t ssrc;
 *     srtp_event_t event;
 * }
 * }
 */
public class srtp_event_data_t {

    srtp_event_data_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_POINTER.withName("session"),
        srtp_h.C_INT.withName("ssrc"),
        srtp_h.C_INT.withName("event")
    ).withName("srtp_event_data_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout session$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("session"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_t session
     * }
     */
    public static final AddressLayout session$layout() {
        return session$LAYOUT;
    }

    private static final long session$OFFSET = $LAYOUT.byteOffset(groupElement("session"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_t session
     * }
     */
    public static final long session$offset() {
        return session$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_t session
     * }
     */
    public static MemorySegment session(MemorySegment struct) {
        return struct.get(session$LAYOUT, session$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_t session
     * }
     */
    public static void session(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(session$LAYOUT, session$OFFSET, fieldValue);
    }

    private static final OfInt ssrc$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ssrc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ssrc
     * }
     */
    public static final OfInt ssrc$layout() {
        return ssrc$LAYOUT;
    }

    private static final long ssrc$OFFSET = $LAYOUT.byteOffset(groupElement("ssrc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ssrc
     * }
     */
    public static final long ssrc$offset() {
        return ssrc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ssrc
     * }
     */
    public static int ssrc(MemorySegment struct) {
        return struct.get(ssrc$LAYOUT, ssrc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ssrc
     * }
     */
    public static void ssrc(MemorySegment struct, int fieldValue) {
        struct.set(ssrc$LAYOUT, ssrc$OFFSET, fieldValue);
    }

    private static final OfInt event$LAYOUT = (OfInt)$LAYOUT.select(groupElement("event"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_event_t event
     * }
     */
    public static final OfInt event$layout() {
        return event$LAYOUT;
    }

    private static final long event$OFFSET = $LAYOUT.byteOffset(groupElement("event"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_event_t event
     * }
     */
    public static final long event$offset() {
        return event$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_event_t event
     * }
     */
    public static int event(MemorySegment struct) {
        return struct.get(event$LAYOUT, event$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_event_t event
     * }
     */
    public static void event(MemorySegment struct, int fieldValue) {
        struct.set(event$LAYOUT, event$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

