// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_policy_t {
 *     srtp_ssrc_t ssrc;
 *     srtp_crypto_policy_t rtp;
 *     srtp_crypto_policy_t rtcp;
 *     uint8_t *key;
 *     srtp_master_key_t **keys;
 *     size_t num_master_keys;
 *     bool use_mki;
 *     size_t mki_size;
 *     size_t window_size;
 *     bool allow_repeat_tx;
 *     uint8_t *enc_xtn_hdr;
 *     size_t enc_xtn_hdr_count;
 *     bool use_cryptex;
 *     struct srtp_policy_t *next;
 * }
 * }
 */
public class srtp_policy_t {

    srtp_policy_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_ssrc_t.layout().withName("ssrc"),
        srtp_crypto_policy_t.layout().withName("rtp"),
        srtp_crypto_policy_t.layout().withName("rtcp"),
        srtp_h.C_POINTER.withName("key"),
        srtp_h.C_POINTER.withName("keys"),
        srtp_h.C_LONG_LONG.withName("num_master_keys"),
        srtp_h.C_BOOL.withName("use_mki"),
        MemoryLayout.paddingLayout(7),
        srtp_h.C_LONG_LONG.withName("mki_size"),
        srtp_h.C_LONG_LONG.withName("window_size"),
        srtp_h.C_BOOL.withName("allow_repeat_tx"),
        MemoryLayout.paddingLayout(7),
        srtp_h.C_POINTER.withName("enc_xtn_hdr"),
        srtp_h.C_LONG_LONG.withName("enc_xtn_hdr_count"),
        srtp_h.C_BOOL.withName("use_cryptex"),
        MemoryLayout.paddingLayout(7),
        srtp_h.C_POINTER.withName("next")
    ).withName("srtp_policy_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ssrc$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ssrc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_ssrc_t ssrc
     * }
     */
    public static final GroupLayout ssrc$layout() {
        return ssrc$LAYOUT;
    }

    private static final long ssrc$OFFSET = $LAYOUT.byteOffset(groupElement("ssrc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_ssrc_t ssrc
     * }
     */
    public static final long ssrc$offset() {
        return ssrc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_ssrc_t ssrc
     * }
     */
    public static MemorySegment ssrc(MemorySegment struct) {
        return struct.asSlice(ssrc$OFFSET, ssrc$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_ssrc_t ssrc
     * }
     */
    public static void ssrc(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ssrc$OFFSET, ssrc$LAYOUT.byteSize());
    }

    private static final GroupLayout rtp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("rtp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtp
     * }
     */
    public static final GroupLayout rtp$layout() {
        return rtp$LAYOUT;
    }

    private static final long rtp$OFFSET = $LAYOUT.byteOffset(groupElement("rtp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtp
     * }
     */
    public static final long rtp$offset() {
        return rtp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtp
     * }
     */
    public static MemorySegment rtp(MemorySegment struct) {
        return struct.asSlice(rtp$OFFSET, rtp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtp
     * }
     */
    public static void rtp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rtp$OFFSET, rtp$LAYOUT.byteSize());
    }

    private static final GroupLayout rtcp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("rtcp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtcp
     * }
     */
    public static final GroupLayout rtcp$layout() {
        return rtcp$LAYOUT;
    }

    private static final long rtcp$OFFSET = $LAYOUT.byteOffset(groupElement("rtcp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtcp
     * }
     */
    public static final long rtcp$offset() {
        return rtcp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtcp
     * }
     */
    public static MemorySegment rtcp(MemorySegment struct) {
        return struct.asSlice(rtcp$OFFSET, rtcp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_crypto_policy_t rtcp
     * }
     */
    public static void rtcp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rtcp$OFFSET, rtcp$LAYOUT.byteSize());
    }

    private static final AddressLayout key$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t *key
     * }
     */
    public static final AddressLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t *key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t *key
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.get(key$LAYOUT, key$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t *key
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(key$LAYOUT, key$OFFSET, fieldValue);
    }

    private static final AddressLayout keys$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_master_key_t **keys
     * }
     */
    public static final AddressLayout keys$layout() {
        return keys$LAYOUT;
    }

    private static final long keys$OFFSET = $LAYOUT.byteOffset(groupElement("keys"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_master_key_t **keys
     * }
     */
    public static final long keys$offset() {
        return keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_master_key_t **keys
     * }
     */
    public static MemorySegment keys(MemorySegment struct) {
        return struct.get(keys$LAYOUT, keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_master_key_t **keys
     * }
     */
    public static void keys(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(keys$LAYOUT, keys$OFFSET, fieldValue);
    }

    private static final OfLong num_master_keys$LAYOUT = (OfLong)$LAYOUT.select(groupElement("num_master_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t num_master_keys
     * }
     */
    public static final OfLong num_master_keys$layout() {
        return num_master_keys$LAYOUT;
    }

    private static final long num_master_keys$OFFSET = $LAYOUT.byteOffset(groupElement("num_master_keys"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t num_master_keys
     * }
     */
    public static final long num_master_keys$offset() {
        return num_master_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t num_master_keys
     * }
     */
    public static long num_master_keys(MemorySegment struct) {
        return struct.get(num_master_keys$LAYOUT, num_master_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t num_master_keys
     * }
     */
    public static void num_master_keys(MemorySegment struct, long fieldValue) {
        struct.set(num_master_keys$LAYOUT, num_master_keys$OFFSET, fieldValue);
    }

    private static final OfBoolean use_mki$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("use_mki"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool use_mki
     * }
     */
    public static final OfBoolean use_mki$layout() {
        return use_mki$LAYOUT;
    }

    private static final long use_mki$OFFSET = $LAYOUT.byteOffset(groupElement("use_mki"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool use_mki
     * }
     */
    public static final long use_mki$offset() {
        return use_mki$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool use_mki
     * }
     */
    public static boolean use_mki(MemorySegment struct) {
        return struct.get(use_mki$LAYOUT, use_mki$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool use_mki
     * }
     */
    public static void use_mki(MemorySegment struct, boolean fieldValue) {
        struct.set(use_mki$LAYOUT, use_mki$OFFSET, fieldValue);
    }

    private static final OfLong mki_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("mki_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t mki_size
     * }
     */
    public static final OfLong mki_size$layout() {
        return mki_size$LAYOUT;
    }

    private static final long mki_size$OFFSET = $LAYOUT.byteOffset(groupElement("mki_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t mki_size
     * }
     */
    public static final long mki_size$offset() {
        return mki_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t mki_size
     * }
     */
    public static long mki_size(MemorySegment struct) {
        return struct.get(mki_size$LAYOUT, mki_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t mki_size
     * }
     */
    public static void mki_size(MemorySegment struct, long fieldValue) {
        struct.set(mki_size$LAYOUT, mki_size$OFFSET, fieldValue);
    }

    private static final OfLong window_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("window_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t window_size
     * }
     */
    public static final OfLong window_size$layout() {
        return window_size$LAYOUT;
    }

    private static final long window_size$OFFSET = $LAYOUT.byteOffset(groupElement("window_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t window_size
     * }
     */
    public static final long window_size$offset() {
        return window_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t window_size
     * }
     */
    public static long window_size(MemorySegment struct) {
        return struct.get(window_size$LAYOUT, window_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t window_size
     * }
     */
    public static void window_size(MemorySegment struct, long fieldValue) {
        struct.set(window_size$LAYOUT, window_size$OFFSET, fieldValue);
    }

    private static final OfBoolean allow_repeat_tx$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("allow_repeat_tx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool allow_repeat_tx
     * }
     */
    public static final OfBoolean allow_repeat_tx$layout() {
        return allow_repeat_tx$LAYOUT;
    }

    private static final long allow_repeat_tx$OFFSET = $LAYOUT.byteOffset(groupElement("allow_repeat_tx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool allow_repeat_tx
     * }
     */
    public static final long allow_repeat_tx$offset() {
        return allow_repeat_tx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool allow_repeat_tx
     * }
     */
    public static boolean allow_repeat_tx(MemorySegment struct) {
        return struct.get(allow_repeat_tx$LAYOUT, allow_repeat_tx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool allow_repeat_tx
     * }
     */
    public static void allow_repeat_tx(MemorySegment struct, boolean fieldValue) {
        struct.set(allow_repeat_tx$LAYOUT, allow_repeat_tx$OFFSET, fieldValue);
    }

    private static final AddressLayout enc_xtn_hdr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("enc_xtn_hdr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t *enc_xtn_hdr
     * }
     */
    public static final AddressLayout enc_xtn_hdr$layout() {
        return enc_xtn_hdr$LAYOUT;
    }

    private static final long enc_xtn_hdr$OFFSET = $LAYOUT.byteOffset(groupElement("enc_xtn_hdr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t *enc_xtn_hdr
     * }
     */
    public static final long enc_xtn_hdr$offset() {
        return enc_xtn_hdr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t *enc_xtn_hdr
     * }
     */
    public static MemorySegment enc_xtn_hdr(MemorySegment struct) {
        return struct.get(enc_xtn_hdr$LAYOUT, enc_xtn_hdr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t *enc_xtn_hdr
     * }
     */
    public static void enc_xtn_hdr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(enc_xtn_hdr$LAYOUT, enc_xtn_hdr$OFFSET, fieldValue);
    }

    private static final OfLong enc_xtn_hdr_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("enc_xtn_hdr_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t enc_xtn_hdr_count
     * }
     */
    public static final OfLong enc_xtn_hdr_count$layout() {
        return enc_xtn_hdr_count$LAYOUT;
    }

    private static final long enc_xtn_hdr_count$OFFSET = $LAYOUT.byteOffset(groupElement("enc_xtn_hdr_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t enc_xtn_hdr_count
     * }
     */
    public static final long enc_xtn_hdr_count$offset() {
        return enc_xtn_hdr_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t enc_xtn_hdr_count
     * }
     */
    public static long enc_xtn_hdr_count(MemorySegment struct) {
        return struct.get(enc_xtn_hdr_count$LAYOUT, enc_xtn_hdr_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t enc_xtn_hdr_count
     * }
     */
    public static void enc_xtn_hdr_count(MemorySegment struct, long fieldValue) {
        struct.set(enc_xtn_hdr_count$LAYOUT, enc_xtn_hdr_count$OFFSET, fieldValue);
    }

    private static final OfBoolean use_cryptex$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("use_cryptex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool use_cryptex
     * }
     */
    public static final OfBoolean use_cryptex$layout() {
        return use_cryptex$LAYOUT;
    }

    private static final long use_cryptex$OFFSET = $LAYOUT.byteOffset(groupElement("use_cryptex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool use_cryptex
     * }
     */
    public static final long use_cryptex$offset() {
        return use_cryptex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool use_cryptex
     * }
     */
    public static boolean use_cryptex(MemorySegment struct) {
        return struct.get(use_cryptex$LAYOUT, use_cryptex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool use_cryptex
     * }
     */
    public static void use_cryptex(MemorySegment struct, boolean fieldValue) {
        struct.set(use_cryptex$LAYOUT, use_cryptex$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct srtp_policy_t *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct srtp_policy_t *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct srtp_policy_t *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct srtp_policy_t *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

