// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct srtp_kernel_cipher_type {
 *     srtp_cipher_type_id_t id;
 *     const srtp_cipher_type_t *cipher_type;
 *     struct srtp_kernel_cipher_type *next;
 * } srtp_kernel_cipher_type_t
 * }
 */
public class srtp_kernel_cipher_type_t extends srtp_kernel_cipher_type {

    srtp_kernel_cipher_type_t() {
        // Should not be called directly
    }
}

