// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct srtp_cipher_type_t {
 *     srtp_cipher_alloc_func_t alloc;
 *     srtp_cipher_dealloc_func_t dealloc;
 *     srtp_cipher_init_func_t init;
 *     srtp_cipher_set_aad_func_t set_aad;
 *     srtp_cipher_encrypt_func_t encrypt;
 *     srtp_cipher_decrypt_func_t decrypt;
 *     srtp_cipher_set_iv_func_t set_iv;
 *     const char *description;
 *     const srtp_cipher_test_case_t *test_data;
 *     srtp_cipher_type_id_t id;
 * }
 * }
 */
public class srtp_cipher_type_t {

    srtp_cipher_type_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_POINTER.withName("alloc"),
        srtp_h.C_POINTER.withName("dealloc"),
        srtp_h.C_POINTER.withName("init"),
        srtp_h.C_POINTER.withName("set_aad"),
        srtp_h.C_POINTER.withName("encrypt"),
        srtp_h.C_POINTER.withName("decrypt"),
        srtp_h.C_POINTER.withName("set_iv"),
        srtp_h.C_POINTER.withName("description"),
        srtp_h.C_POINTER.withName("test_data"),
        srtp_h.C_INT.withName("id"),
        MemoryLayout.paddingLayout(4)
    ).withName("srtp_cipher_type_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout alloc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("alloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_alloc_func_t alloc
     * }
     */
    public static final AddressLayout alloc$layout() {
        return alloc$LAYOUT;
    }

    private static final long alloc$OFFSET = $LAYOUT.byteOffset(groupElement("alloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_alloc_func_t alloc
     * }
     */
    public static final long alloc$offset() {
        return alloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_alloc_func_t alloc
     * }
     */
    public static MemorySegment alloc(MemorySegment struct) {
        return struct.get(alloc$LAYOUT, alloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_alloc_func_t alloc
     * }
     */
    public static void alloc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(alloc$LAYOUT, alloc$OFFSET, fieldValue);
    }

    private static final AddressLayout dealloc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dealloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_dealloc_func_t dealloc
     * }
     */
    public static final AddressLayout dealloc$layout() {
        return dealloc$LAYOUT;
    }

    private static final long dealloc$OFFSET = $LAYOUT.byteOffset(groupElement("dealloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_dealloc_func_t dealloc
     * }
     */
    public static final long dealloc$offset() {
        return dealloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_dealloc_func_t dealloc
     * }
     */
    public static MemorySegment dealloc(MemorySegment struct) {
        return struct.get(dealloc$LAYOUT, dealloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_dealloc_func_t dealloc
     * }
     */
    public static void dealloc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dealloc$LAYOUT, dealloc$OFFSET, fieldValue);
    }

    private static final AddressLayout init$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_init_func_t init
     * }
     */
    public static final AddressLayout init$layout() {
        return init$LAYOUT;
    }

    private static final long init$OFFSET = $LAYOUT.byteOffset(groupElement("init"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_init_func_t init
     * }
     */
    public static final long init$offset() {
        return init$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_init_func_t init
     * }
     */
    public static MemorySegment init(MemorySegment struct) {
        return struct.get(init$LAYOUT, init$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_init_func_t init
     * }
     */
    public static void init(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init$LAYOUT, init$OFFSET, fieldValue);
    }

    private static final AddressLayout set_aad$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_aad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_set_aad_func_t set_aad
     * }
     */
    public static final AddressLayout set_aad$layout() {
        return set_aad$LAYOUT;
    }

    private static final long set_aad$OFFSET = $LAYOUT.byteOffset(groupElement("set_aad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_set_aad_func_t set_aad
     * }
     */
    public static final long set_aad$offset() {
        return set_aad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_set_aad_func_t set_aad
     * }
     */
    public static MemorySegment set_aad(MemorySegment struct) {
        return struct.get(set_aad$LAYOUT, set_aad$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_set_aad_func_t set_aad
     * }
     */
    public static void set_aad(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_aad$LAYOUT, set_aad$OFFSET, fieldValue);
    }

    private static final AddressLayout encrypt$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("encrypt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_encrypt_func_t encrypt
     * }
     */
    public static final AddressLayout encrypt$layout() {
        return encrypt$LAYOUT;
    }

    private static final long encrypt$OFFSET = $LAYOUT.byteOffset(groupElement("encrypt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_encrypt_func_t encrypt
     * }
     */
    public static final long encrypt$offset() {
        return encrypt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_encrypt_func_t encrypt
     * }
     */
    public static MemorySegment encrypt(MemorySegment struct) {
        return struct.get(encrypt$LAYOUT, encrypt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_encrypt_func_t encrypt
     * }
     */
    public static void encrypt(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(encrypt$LAYOUT, encrypt$OFFSET, fieldValue);
    }

    private static final AddressLayout decrypt$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("decrypt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_decrypt_func_t decrypt
     * }
     */
    public static final AddressLayout decrypt$layout() {
        return decrypt$LAYOUT;
    }

    private static final long decrypt$OFFSET = $LAYOUT.byteOffset(groupElement("decrypt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_decrypt_func_t decrypt
     * }
     */
    public static final long decrypt$offset() {
        return decrypt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_decrypt_func_t decrypt
     * }
     */
    public static MemorySegment decrypt(MemorySegment struct) {
        return struct.get(decrypt$LAYOUT, decrypt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_decrypt_func_t decrypt
     * }
     */
    public static void decrypt(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(decrypt$LAYOUT, decrypt$OFFSET, fieldValue);
    }

    private static final AddressLayout set_iv$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_iv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_set_iv_func_t set_iv
     * }
     */
    public static final AddressLayout set_iv$layout() {
        return set_iv$LAYOUT;
    }

    private static final long set_iv$OFFSET = $LAYOUT.byteOffset(groupElement("set_iv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_set_iv_func_t set_iv
     * }
     */
    public static final long set_iv$offset() {
        return set_iv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_set_iv_func_t set_iv
     * }
     */
    public static MemorySegment set_iv(MemorySegment struct) {
        return struct.get(set_iv$LAYOUT, set_iv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_set_iv_func_t set_iv
     * }
     */
    public static void set_iv(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_iv$LAYOUT, set_iv$OFFSET, fieldValue);
    }

    private static final AddressLayout description$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final AddressLayout description$layout() {
        return description$LAYOUT;
    }

    private static final long description$OFFSET = $LAYOUT.byteOffset(groupElement("description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final long description$offset() {
        return description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static MemorySegment description(MemorySegment struct) {
        return struct.get(description$LAYOUT, description$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static void description(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(description$LAYOUT, description$OFFSET, fieldValue);
    }

    private static final AddressLayout test_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("test_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const srtp_cipher_test_case_t *test_data
     * }
     */
    public static final AddressLayout test_data$layout() {
        return test_data$LAYOUT;
    }

    private static final long test_data$OFFSET = $LAYOUT.byteOffset(groupElement("test_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const srtp_cipher_test_case_t *test_data
     * }
     */
    public static final long test_data$offset() {
        return test_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const srtp_cipher_test_case_t *test_data
     * }
     */
    public static MemorySegment test_data(MemorySegment struct) {
        return struct.get(test_data$LAYOUT, test_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const srtp_cipher_test_case_t *test_data
     * }
     */
    public static void test_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(test_data$LAYOUT, test_data$OFFSET, fieldValue);
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * srtp_cipher_type_id_t id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

