// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t H[5];
 *     uint32_t M[16];
 *     size_t octets_in_buffer;
 *     uint32_t num_bits_in_msg;
 * }
 * }
 */
public class srtp_sha1_ctx_t {

    srtp_sha1_ctx_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, srtp_h.C_INT).withName("H"),
        MemoryLayout.sequenceLayout(16, srtp_h.C_INT).withName("M"),
        MemoryLayout.paddingLayout(4),
        srtp_h.C_LONG_LONG.withName("octets_in_buffer"),
        srtp_h.C_INT.withName("num_bits_in_msg"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$61:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout H$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("H"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static final SequenceLayout H$layout() {
        return H$LAYOUT;
    }

    private static final long H$OFFSET = $LAYOUT.byteOffset(groupElement("H"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static final long H$offset() {
        return H$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static MemorySegment H(MemorySegment struct) {
        return struct.asSlice(H$OFFSET, H$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static void H(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, H$OFFSET, H$LAYOUT.byteSize());
    }

    private static long[] H$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static long[] H$dimensions() {
        return H$DIMS;
    }
    private static final VarHandle H$ELEM_HANDLE = H$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static int H(MemorySegment struct, long index0) {
        return (int)H$ELEM_HANDLE.get(struct, H$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t H[5]
     * }
     */
    public static void H(MemorySegment struct, long index0, int fieldValue) {
        H$ELEM_HANDLE.set(struct, H$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout M$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("M"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static final SequenceLayout M$layout() {
        return M$LAYOUT;
    }

    private static final long M$OFFSET = $LAYOUT.byteOffset(groupElement("M"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static final long M$offset() {
        return M$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static MemorySegment M(MemorySegment struct) {
        return struct.asSlice(M$OFFSET, M$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static void M(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, M$OFFSET, M$LAYOUT.byteSize());
    }

    private static long[] M$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static long[] M$dimensions() {
        return M$DIMS;
    }
    private static final VarHandle M$ELEM_HANDLE = M$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static int M(MemorySegment struct, long index0) {
        return (int)M$ELEM_HANDLE.get(struct, M$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t M[16]
     * }
     */
    public static void M(MemorySegment struct, long index0, int fieldValue) {
        M$ELEM_HANDLE.set(struct, M$OFFSET, index0, fieldValue);
    }

    private static final OfLong octets_in_buffer$LAYOUT = (OfLong)$LAYOUT.select(groupElement("octets_in_buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t octets_in_buffer
     * }
     */
    public static final OfLong octets_in_buffer$layout() {
        return octets_in_buffer$LAYOUT;
    }

    private static final long octets_in_buffer$OFFSET = $LAYOUT.byteOffset(groupElement("octets_in_buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t octets_in_buffer
     * }
     */
    public static final long octets_in_buffer$offset() {
        return octets_in_buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t octets_in_buffer
     * }
     */
    public static long octets_in_buffer(MemorySegment struct) {
        return struct.get(octets_in_buffer$LAYOUT, octets_in_buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t octets_in_buffer
     * }
     */
    public static void octets_in_buffer(MemorySegment struct, long fieldValue) {
        struct.set(octets_in_buffer$LAYOUT, octets_in_buffer$OFFSET, fieldValue);
    }

    private static final OfInt num_bits_in_msg$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_bits_in_msg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t num_bits_in_msg
     * }
     */
    public static final OfInt num_bits_in_msg$layout() {
        return num_bits_in_msg$LAYOUT;
    }

    private static final long num_bits_in_msg$OFFSET = $LAYOUT.byteOffset(groupElement("num_bits_in_msg"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t num_bits_in_msg
     * }
     */
    public static final long num_bits_in_msg$offset() {
        return num_bits_in_msg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t num_bits_in_msg
     * }
     */
    public static int num_bits_in_msg(MemorySegment struct) {
        return struct.get(num_bits_in_msg$LAYOUT, num_bits_in_msg$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t num_bits_in_msg
     * }
     */
    public static void num_bits_in_msg(MemorySegment struct, int fieldValue) {
        struct.set(num_bits_in_msg$LAYOUT, num_bits_in_msg$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

