// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct srtp_kernel_debug_module {
 *     srtp_debug_module_t *mod;
 *     struct srtp_kernel_debug_module *next;
 * } srtp_kernel_debug_module_t
 * }
 */
public class srtp_kernel_debug_module_t extends srtp_kernel_debug_module {

    srtp_kernel_debug_module_t() {
        // Should not be called directly
    }
}

