// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct timespec {
 *     time_t tv_sec;
 *     long tv_nsec;
 * }
 * }
 */
public class timespec {

    timespec() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        srtp_h.C_LONG_LONG.withName("tv_sec"),
        srtp_h.C_LONG.withName("tv_nsec"),
        MemoryLayout.paddingLayout(4)
    ).withName("timespec");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final ValueLayout tv_sec$LAYOUT = (ValueLayout)$LAYOUT.select(groupElement("tv_sec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * time_t tv_sec
     * }
     */
    public static final ValueLayout tv_sec$layout() { return tv_sec$LAYOUT; }

    private static final long tv_sec$OFFSET = $LAYOUT.byteOffset(groupElement("tv_sec"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * time_t tv_sec
     * }
     */
    public static final long tv_sec$offset() {
        return tv_sec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * time_t tv_sec
     * }
     */
    public static long tv_sec(MemorySegment struct) {
        if (tv_sec$LAYOUT instanceof OfInt oi) return struct.get(oi, tv_sec$OFFSET);
        if (tv_sec$LAYOUT instanceof OfLong ol) return struct.get(ol, tv_sec$OFFSET);
        throw new UnsupportedOperationException("Unsupported layout type: " + tv_sec$LAYOUT);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * time_t tv_sec
     * }
     */
    public static void tv_sec(MemorySegment struct, long fieldValue) {
        if (tv_sec$LAYOUT instanceof OfInt oi) {
            struct.set(oi, tv_sec$OFFSET, (int) fieldValue);
        } else if (tv_sec$LAYOUT instanceof OfLong ol) {
            struct.set(ol, tv_sec$OFFSET, fieldValue);
        }
    }

    private static final ValueLayout tv_nsec$LAYOUT = (ValueLayout)$LAYOUT.select(groupElement("tv_nsec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static final ValueLayout tv_nsec$layout() { return tv_nsec$LAYOUT; }

    private static final long tv_nsec$OFFSET = $LAYOUT.byteOffset(groupElement("tv_nsec"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static final long tv_nsec$offset() {
        return tv_nsec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static long tv_nsec(MemorySegment struct) {
        if (tv_nsec$LAYOUT instanceof OfInt oi) return struct.get(oi, tv_nsec$OFFSET);
        if (tv_nsec$LAYOUT instanceof OfLong ol) return struct.get(ol, tv_nsec$OFFSET);
        throw new UnsupportedOperationException("Unsupported layout type: " + tv_nsec$LAYOUT);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long tv_nsec
     * }
     */
    public static void tv_nsec(MemorySegment struct, long fieldValue) {
        if (tv_nsec$LAYOUT instanceof OfInt oi) {
            struct.set(oi, tv_nsec$OFFSET, (int) fieldValue);
        } else if (tv_nsec$LAYOUT instanceof OfLong ol) {
            struct.set(ol, tv_nsec$OFFSET, fieldValue);
        }
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

