// Generated by jextract

package io.github.kinsleykajiva.libsrtp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union {
 *     uint8_t v8[16];
 *     uint16_t v16[8];
 *     uint32_t v32[4];
 *     uint64_t v64[2];
 * }
 * }
 */
public class v128_t {

    v128_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(16, srtp_h.C_CHAR).withName("v8"),
        MemoryLayout.sequenceLayout(8, srtp_h.C_SHORT).withName("v16"),
        MemoryLayout.sequenceLayout(4, srtp_h.C_INT).withName("v32"),
        MemoryLayout.sequenceLayout(2, srtp_h.C_LONG_LONG).withName("v64")
    ).withName("$anon$72:9");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout v8$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("v8"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static final SequenceLayout v8$layout() {
        return v8$LAYOUT;
    }

    private static final long v8$OFFSET = $LAYOUT.byteOffset(groupElement("v8"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static final long v8$offset() {
        return v8$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static MemorySegment v8(MemorySegment union) {
        return union.asSlice(v8$OFFSET, v8$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static void v8(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, v8$OFFSET, v8$LAYOUT.byteSize());
    }

    private static long[] v8$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static long[] v8$dimensions() {
        return v8$DIMS;
    }
    private static final VarHandle v8$ELEM_HANDLE = v8$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static byte v8(MemorySegment union, long index0) {
        return (byte)v8$ELEM_HANDLE.get(union, v8$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t v8[16]
     * }
     */
    public static void v8(MemorySegment union, long index0, byte fieldValue) {
        v8$ELEM_HANDLE.set(union, v8$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout v16$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("v16"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static final SequenceLayout v16$layout() {
        return v16$LAYOUT;
    }

    private static final long v16$OFFSET = $LAYOUT.byteOffset(groupElement("v16"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static final long v16$offset() {
        return v16$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static MemorySegment v16(MemorySegment union) {
        return union.asSlice(v16$OFFSET, v16$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static void v16(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, v16$OFFSET, v16$LAYOUT.byteSize());
    }

    private static long[] v16$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static long[] v16$dimensions() {
        return v16$DIMS;
    }
    private static final VarHandle v16$ELEM_HANDLE = v16$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static short v16(MemorySegment union, long index0) {
        return (short)v16$ELEM_HANDLE.get(union, v16$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint16_t v16[8]
     * }
     */
    public static void v16(MemorySegment union, long index0, short fieldValue) {
        v16$ELEM_HANDLE.set(union, v16$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout v32$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("v32"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static final SequenceLayout v32$layout() {
        return v32$LAYOUT;
    }

    private static final long v32$OFFSET = $LAYOUT.byteOffset(groupElement("v32"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static final long v32$offset() {
        return v32$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static MemorySegment v32(MemorySegment union) {
        return union.asSlice(v32$OFFSET, v32$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static void v32(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, v32$OFFSET, v32$LAYOUT.byteSize());
    }

    private static long[] v32$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static long[] v32$dimensions() {
        return v32$DIMS;
    }
    private static final VarHandle v32$ELEM_HANDLE = v32$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static int v32(MemorySegment union, long index0) {
        return (int)v32$ELEM_HANDLE.get(union, v32$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t v32[4]
     * }
     */
    public static void v32(MemorySegment union, long index0, int fieldValue) {
        v32$ELEM_HANDLE.set(union, v32$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout v64$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("v64"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static final SequenceLayout v64$layout() {
        return v64$LAYOUT;
    }

    private static final long v64$OFFSET = $LAYOUT.byteOffset(groupElement("v64"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static final long v64$offset() {
        return v64$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static MemorySegment v64(MemorySegment union) {
        return union.asSlice(v64$OFFSET, v64$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static void v64(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, v64$OFFSET, v64$LAYOUT.byteSize());
    }

    private static long[] v64$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static long[] v64$dimensions() {
        return v64$DIMS;
    }
    private static final VarHandle v64$ELEM_HANDLE = v64$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static long v64(MemorySegment union, long index0) {
        return (long)v64$ELEM_HANDLE.get(union, v64$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint64_t v64[2]
     * }
     */
    public static void v64(MemorySegment union, long index0, long fieldValue) {
        v64$ELEM_HANDLE.set(union, v64$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

